[scripts][qemu] synchronize tun/tap and ethernet device selection switches on all arches

diff --git a/scripts/do-qemuriscv b/scripts/do-qemuriscv
--- a/scripts/do-qemuriscv
+++ b/scripts/do-qemuriscv
@@ -20,6 +20,7 @@ function HELP {
     echo "-A <cmd line>     : append command line (may be used multiple times)"
     echo "-d <disk image>   : add a virtio block device (may be used multiple times)"
     echo "-n                : add a virtio network device (user mode networking)"
+    echo "-N <network driver> : specify network driver (requires -n or -t, e.g., virtio-net-device, virtio-net-pci)"
     echo "-t                : add a virtio tap network device (requires tap interface setup)"
     echo "-g                : add a virtio display (GPU, keyboard, mouse)"
     echo "-C                : PCI based virtio devices"
@@ -46,8 +47,10 @@ MEMSIZE=0
 SUDO=""
 PROJECT=""
 DO_DRYRUN=0
+NETDEV=""
+DO_NETDEV_OVERRIDE=0
 
-while getopts A:cCd:ghm:Mmnteu6p:s:SX FLAG; do
+while getopts A:cCd:ghm:MmntN:eu6p:s:SX FLAG; do
     case $FLAG in
         A) CMDLINE+="${CMDLINE:+ }$(quote_cmdline_arg "$OPTARG")";;
         c) DO_CMPCTMALLOC=1;;
@@ -59,6 +62,7 @@ while getopts A:cCd:ghm:Mmnteu6p:s:SX FLAG; do
         M) DO_MINIHEAP=1;;
         n) DO_NET=1;;
         t) DO_NET_TAP=1;;
+        N) NETDEV=$OPTARG; DO_NETDEV_OVERRIDE=1;;
         e) DO_EMBEDDED=1;;
         u) DO_UNLEASHED=1;;
         6) DO_64BIT=1;;
@@ -75,6 +79,16 @@ while getopts A:cCd:ghm:Mmnteu6p:s:SX FLAG; do
 done
 
 shift $((OPTIND-1))
+
+if (( DO_NET && DO_NET_TAP )); then
+    echo "Error: Cannot use both -n (user network) and -t (tap network) together"
+    exit 1
+fi
+
+if (( DO_NETDEV_OVERRIDE && ! ( DO_NET || DO_NET_TAP ) )); then
+    echo "Error: -N requires either -n (user network) or -t (tap network)"
+    exit 1
+fi
 
 CPU=""
 BIOS=""
@@ -141,6 +155,10 @@ else
     VIRTIO_RNG_DEVICE="virtio-rng-device"
 fi
 
+if (( ! DO_NETDEV_OVERRIDE )); then
+    NETDEV="$VIRTIO_NET_DEVICE"
+fi
+
 # construct a list of args based on previous variables using arrays
 ARGS=()
 ARGS+=("-machine" "$MACHINE")
@@ -172,18 +190,19 @@ for img in "${DISK_IMAGES[@]}"; do
 done
 if (( DO_NET )); then
     ARGS+=("-netdev" "user,id=vmnic,hostname=qemu")
-    ARGS+=("-device" "${VIRTIO_NET_DEVICE},netdev=vmnic")
-fi
-if (( DO_NET_TAP )); then
+    ARGS+=("-device" "${NETDEV},netdev=vmnic")
+elif (( DO_NET_TAP )); then
     # quick note to enable tap interface
     # IFNAME=qemu0
     # BRIDGE=bridge0
-    # sudo tunctl -u $(whoami) -t ${IFNAME}
-    # sudo ifconfig ${IFNAME} up
-    # sudo ip link set ${IFNAME} master ${BRIDGE}
+    # sudo ip tuntap add name "${IFNAME}" mode tap user $(whoami)
+    # sudo ip link set "${IFNAME}" master "${BRIDGE}"
+    # sudo ip link set "${IFNAME}" up
     ARGS+=("-netdev" "tap,id=vmnic,ifname=qemu0,script=no,downscript=no")
-    ARGS+=("-device" "${VIRTIO_NET_DEVICE},netdev=vmnic")
+    ARGS+=("-device" "${NETDEV},netdev=vmnic")
     #SUDO="sudo"
+else
+    ARGS+=("-net" "none")
 fi
 if (( DO_DISPLAY )); then
     ARGS+=("-device" "${VIRTIO_GPU_DEVICE}")
